# ------------------------------------------------------------------------------
# Example configuration file for Cresbot.
# ------------------------------------------------------------------------------

# the directory to keep logs in
log_dir = '/path/to/logs'

# the credentials for logging into the api with
username = 'username@name'
password = 'password_token'
