%YAML 1.1
---
# to test, see <http://yaml-online-parser.appspot.com/>

api                   : null
api_config            : {defaults: {maxlag: 5}}
api_url               : http://communitytest.wikia.com/api.php
api_username          : USERNAME
api_password          : PASSWORD

log_file              : /home/username/cresbot/logs/cresbot.log
log_file_level        : DEBUG
log_email             : true
log_email_level       : ERROR
log_email_mailhost    :
    - smtp.gmail.com
    - 587
log_email_from        : foo@bar.com
log_email_to          :
    - bar@foo.com
log_email_subject     : Cresbot Error
log_email_credentials :
    - foo@bar.com
    - PASSWORD
log_email_secure      : []

tasks                 : null
