%YAML 1.1 # Cresbot config file
---
# api config
api              : null
api_config       : {defaults: {maxlag: 5}}
api_url          : http://communitytest.wikia.com/api.php
api_username     : USERNAME
api_password     : PASSWORD

# log config
log_file         : /var/log/cresbot.log
log_level_file   : DEBUG
log_level_stream : INFO

# task config
tasks            : null
